apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app
  namespace: payments
  labels:
    app: payments-app
    app.kubernetes.io/part-of: observability-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-app
  template:
    metadata:
      labels:
        app: payments-app
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  namespace: payments
  labels:
    app: payments-worker
    purpose: light-load
    app.kubernetes.io/part-of: observability-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
        purpose: light-load
    spec:
      containers:
        - name: stress-ng
          image: alexeiled/stress-ng:latest
          args:
            - "--cpu"
            - "1"
            - "--cpu-load"
            - "30"
            - "--timeout"
            - "0"
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              memory: "128Mi"
